# Generated by Django 5.2.7 on 2025-11-23 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraIndependiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('nombre_autor', models.CharField(default='Anónimo', max_length=100, verbose_name='Nombre público del Autor/Director')),
                ('descripcion', models.TextField()),
                ('url_video', models.URLField(max_length=500)),
                ('imagen_portada', models.ImageField(default='portadas/default.jpg', upload_to='portadas/independiente/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('rating_promedio', models.DecimalField(decimal_places=1, default=8.5, max_digits=3)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras_independientes', to='app_base.categoria', verbose_name='Categoría/Género Principal')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Propina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('espectador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_creadores.obraindependiente')),
            ],
        ),
    ]
