# Generated by Django 5.2.7 on 2025-11-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0002_initial'),
        ('app_creadores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obraindependiente',
            name='categoria',
        ),
        migrations.AddField(
            model_name='obraindependiente',
            name='categoria',
            field=models.ManyToManyField(related_name='obras_independientes', to='app_base.categoria', verbose_name='Categoría/Género Principal'),
        ),
    ]
