# Generated by Django 5.2.7 on 2025-11-23 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeliculaHuerfana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('nombre_autor', models.CharField(blank=True, default='Desconocido', max_length=100, null=True, verbose_name='Autor/Director conocido')),
                ('anio_estimado', models.IntegerField(blank=True, null=True, verbose_name='Año Estimado')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url_video', models.URLField(blank=True, max_length=500, null=True)),
                ('imagen_portada', models.ImageField(default='portadas/default_huerfana.jpg', upload_to='portadas/huerfanas/')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('categorias', models.ManyToManyField(related_name='peliculas_huerfanas', to='app_base.categoria')),
            ],
            options={
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='SugerenciaMetadato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_sugerido', models.CharField(max_length=100)),
                ('valor_propuesto', models.TextField()),
                ('fecha_sugerencia', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de Revisión'), ('Aceptado', 'Aceptado y Aplicado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias', to='app_conservacion.peliculahuerfana')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la sugerencia', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sugerencias de Metadatos',
            },
        ),
    ]
